### ISSUE TITLE
What is file into the CameraMode?

### ISSUE THREAD

**Issue by GeekBugs** [bouviervj/ORB_SLAM2_AndroidStudio#3]
Hi, I Build your project,it can works,but I don't know what is two files into the CameraMode

Can you help me provide files?

Now,I put into Asus.yaml ，but what is the file of voc?

**Comment by mafanwei** [comment]
How to build this? Can you help me

**Comment by GeekBugs** [comment]
> How to build this? Can you help me

Sorry, I delete this project in my computer.
